# SPDX-License-Identifier: Apache-2.0
# # Copyright Contributors to the ODPi Egeria project.
# no change
name: Egeria UI Build

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          # Polymer requires Node 10 LTS (not 12,14)
          node-version: "10.13.0"
      - name: Report npm and node version
        run: |
          node -v
          npm -v
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
      # Get package version from the package.json
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.check.outputs.changed == 'true' }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to container registry (Quay.io)
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_ACCESS_TOKEN }}
      # For main code stream we push the image and add the latest tag
      - name: Build and push (master merge)
        id: docker_build_master
        uses: docker/build-push-action@v2
        with:
          push:  true
          tags: tcnthomas/egeria-ui:${{ steps.package-version.outputs.current-version }}, tcnthomas/egeria-ui:latest, quay.io/tcnthomas/egeria-ui:${{ steps.package-version.outputs.current-version }}, quay.io/tcnthomas/egeria-ui:latest
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
      # Note the digest
      - name: Image digest (master)
        run: echo ${{ steps.docker_build_master.outputs.digest }}
      # Save an artifact of the build tree & upload
      - name: Create Archive
        if: ${{ steps.check.outputs.changed == 'true' }}
        run: tar -zcf /tmp/egeria-ui.tar.gz .
      - name: Upload
        uses: actions/upload-artifact@v2
        if: ${{ steps.check.outputs.changed == 'true' }}
        with:
          name: Egeria UI ${{ steps.package-version.outputs.current-version }}
          path: /tmp/egeria-ui.tar.gz
